exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('content').del()
    .then(function () {
      // Inserts seed entries
      return knex('content').insert([
        {id: 1, name: "The Carinhall", description: "Fifty years before the war between gods came to it's conclusion, The Carinhall was established, appropriately named after the founding hunter Dahn Carin, and has become the epicenter for temporary contracted work and hunting of the fiercest beasts known. Any citizen wishing work to be done, whether it be dangerous beast or transporting goods, can come to The Carinhall and offer reward for services rendered. Carinhall Members receive access to special missions hosting significantly more dangerous prey. Members can be identified by a magical branding on the shoulders, the symbol of the Lyall. Contracts are magically bound to the hunter who accepted the contract and any other Carinhall member that poaches a bound contract is subject to expulsion from the guild and/or death. Two massive tree trunks fifteen feet in diameter make the pillars of the Grand Archway that leads to the main hall. Immediately after walking in, you'll notice a fire pit directly in the center of the hall, surrounded by massive stone slabs resting on boulders forming a three-quarter circular table around the twenty foot tall blaze. Smoke billows into the open air through a vent hole in the ceiling some one hundred and fifty feet up. Carinhall members, triumphant from the hunt, will host feasts at this table for any wishing to celebrate.", catagory_id: 1},
        {id: 2, name: "Infinite Arcanum", description: "Overview and History: All of the realms greatest mages fought during the War between Gods. They saw the incursion of demons, devils, and lich firsthand and were rightly terrified that the spawn of the Betrayer Gods could ever return to the realm. It was clear the celestial gate did not wholly prevent the supernatural from infringing upon the world. These mages of X'yllisan are charged with preventing future incursions and trying to avoid the many mistakes made during the war. Considering this, Erimel Ervanion, a High Elven Assemblyman who is well studied within the Lyceum and a well-respected arcanist, called to the realm’s most trusted and capable mages, and together they formed a private society called the Infinite Arcanum in AA-990. The chief priority of these powerful arcane specialists is to maintain the “Truth of Magic,” a strict code enacted to never again allow the rampant misuse of magic that was seen in the war. General members are referred to as “Guides,” while the higher circle of members who deal in judgment and oversight are called “Makers.” Membership is largely kept secret unless out of necessity, though the existence of the order is relatively common knowledge. Anyone found to be practicing magic is logged and checked up on routinely, as misuse of magic is grounds for arrest, judgment by the Makers, and punishment outside of the local law. Even so, their reach and oversight are not without limits, and many dark and terrible dealings still manage to go unseen.", catagory_id: 1},
        {id: 3, name: "The Alabaster Lyceum", description: "The imposing white buildings at the center of Tirgonde that stands before you is home to the largest gathering of written forms of knowledge in the land. Many, from all walks of life, call the Lyceum home and learn everything they can of history, politics, and business. Some users of the arcane rely on their patron deity for power; others still develop their arcane skill by seeking admission to the Alabaster Lyceum, where they can study the theory and apllication of magic in a controlled environment.", catagory_id: 1},
        {id: 4, name: "City of Alleduhn", description: "Foresting City proper", catagory_id: 2},
        {id: 5, name: "Alleduhn Ports", description: "Main trading hub for Alleduhn and Headquarters to The Carinhall", catagory_id: 2},
        {id: 6, name: "City of Tirgonde", description: "Main Societal Center", catagory_id: 2},
        {id: 7, name: "Magnate", description: "Lorenal I think. I have notes some where, I swear.", catagory_id: 3},
        {id: 8, name: "Frederick Gammund", description: "Right hand of the Magnate", catagory_id: 3},
        {id: 9, name: "Another person of Interest", description: "Interesting details about the person of interest", catagory_id: 3},
        {id: 10, name: "The Platinum Dragon", description: "A big badass dragon", catagory_id: 4},
        {id: 11, name: "Another Diety", description: "Deets about the diety", catagory_id: 4},
        {id: 12, name: "The Last Diety", description: "More deets about another diety", catagory_id: 4}
      ]);
    });
};