
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('additionaldata').del()
    .then(function () {
      // Inserts seed entries
      return knex('additionaldata').insert([
        {id: 1, title: 'Gerolf', description: "The Grandmaster. There is only one, the title, respect, and authority is given to anyone that can bring in a trophy from a hunt that is equal to or greater than the current leaders most prestigious trophy. The Gerolf and the Challenger will then be given a hunt each to complete on their own. They are given 3 days to complete the hunt. Should both succeed, they will fight in hand to hand combat until only one stands. If one falls at any point in time, the survivor wins. If both fail, the most senior Lyall takes over until unseated."},
        {id: 2, title: 'Lyall', description: "Full members of the Carinhall. Lyalls have access to Rank SS, Rank S, Rank A, Rank B, and Rank C contracts going through the guild with no restriction. Lyalls are responsible for maintaining the Hall, it's facilities and services along with other administrative tasks. These are usually reserved for the Lyalls that are not fit for combat, but have not outlived their usefulness and are generally very well respected. Lyalls on active hunting status will sponsor and mentor one Wolf and two Initiate."},
        {id: 3, title: 'Wolf', description: "This title is given to a teams most senior Initiate, if they have earned it. An Wolf is usually just as capable as the Lyall, reaching the advanced stages of training. They are primarily responsible for any additional or corrective training any Initiates may need. An Wolf has access to Rank B and C contracts. If a Wolf takes a higher ranking hunt, they may include all, any, or none of their Initiates, magically binding them to the contract as well. A Wolf may only become a Lyall if their Lyall either becomes the Gerolf, dies, or transfers to an inactive status. Additionally, if a Wolf is able to provide proof of worthy and successful hunt, the Gerolf may promote that Wolf to Lyall."},
        {id: 4, title: 'Initiate', description: "Initiates are still given the guild brand though they are only allowed to complete Rank C contracts. In order to become an Initiate, a prospective member must prove proficiency with hunting in general. For example, if a person were to bring the hide of a recently killed bear, can prove they were the one responsible for the kill, they will be presented to the Gerolf for approval. If the Gerolf believes a person to be capable, they will be assigned to a Lyall that will oversee an official guild hunt. Should the aspiring Initiate succeed in completing the task given, they will be ceremoniously branded and welcomed as an officially and permanently assigned to a Lyall."}
      ]);
    });
};
